modLoader="javafml"
loaderVersion="[41,)"
license="https://raw.githubusercontent.com/dcaedll/OminousDarkness/main/LICENSE"
issueTrackerURL="https://github.com/dcaedll/OminousDarkness/issues"

[[mods]]
modId="ominousdarkness"
version="${file.jarVersion}"
displayName="Ominous Darkness"
updateJSONURL="https://raw.githubusercontent.com/dcaedll/OminousDarkness/main/update.json"
displayURL="https://github.com/dcaedll/OminousDarkness"
logoFile="ominous_darkness_logo.png"
credits="toujourspareil https://twitter.com/toujourspareil_"
authors="dcaedll"
displayTest="MATCH_VERSION"
description='''
Being in the darkness for too long is now life-threatening, as you start feeling the presence of something evil within.

This mod makes exploration and adventures a whole lot more difficult; now you're hunted by the darkness itself!
Simply being out in the darkness for too long kills you (this behavior can be changed in the config), effectively rendering your exploration capabilities limited.
Watch out and make sure to bring some light with you to dispel the darkness!
'''

[[dependencies.ominousdarkness]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
